runtime: python39  # Specify the Python runtime version. Ensure it matches the version you're using.

entrypoint: gunicorn -b :$PORT main:app  # Configure Gunicorn as the WSGI server to serve your app.

env_variables:
  # Environment variables ensure your application uses the correct database credentials and connection settings.
  # Replace these placeholders with your actual database credentials and Google Cloud SQL connection names.
  SQL_USER: "root"
  SQL_PASSWORD: "pass"
  SQL_DATABASE: "foodies"
  SQL_CONNECTION_NAME: "instance"
  # Example: project-id:us-central1:instance-name
  
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5  # Configure these to the desired scale based on your expected load.

beta_settings:
  cloud_sql_instances: "cloudinstance"  # Enables connection to Cloud SQL

handlers:
- url: /static
  static_dir: static/  # Configure this if your app includes static resources like images, CSS, JavaScript, etc.

- url: /.*
  script: auto
  secure: always  # Forces HTTPS

# If your application uses session or other sensitive data, configure session management properly.
